name: flutter_sticky_header
description: Flutter implementation of sticky headers as a sliver. Use it in a CustomScrollView.
version: 1.0.0
homepage: https://github.com/letsar/flutter_sticky_header

dependencies:
  flutter:
    sdk: flutter
  value_layout_builder: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sliver_tools: ^0.2.7

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.0.0"
